jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
   
  steps:
  - checkout: self
    submodules: true
  
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  
  - script: conda create --yes --quiet --name nthits
    displayName: Create Anaconda environment

  - script: |
      source activate nthits
      conda install --yes -c conda-forge -c bioconda --file requirements.txt
    displayName: Install dependencies

  - script: |
      source activate nthits
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits

- job:
  displayName: MacOS
  pool:
    vmImage: 'macOS-latest'
  
  steps:
  - checkout: self
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  
  - script: conda create --yes --quiet --name nthits
    displayName: Create Anaconda environment

  - script: |
      source activate nthits
      conda install --yes -c conda-forge python=3.10
      conda install --yes -c conda-forge c-compiler cxx-compiler openmp meson cmake catch2
      conda install --yes -c bioconda btllib
    displayName: Install dependencies

  - script: |
      source activate nthits
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits
