jobs:

- job: linux
  pool:
    vmImage: 'ubuntu-22.04'
   
  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      conda create --yes --quiet --name nthits
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Create Anaconda environment
    
  - script: |
      conda activate nthits
      conda install --yes --file requirements.txt
    displayName: Install dependencies
    
  - script: |
      conda activate nthits
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits

- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda create --yes --quiet --name nthits
    displayName: Create Anaconda environment
    
  - script: |
      conda activate nthits
      conda install --yes --file requirements.txt
    displayName: Install dependencies
    
  - script: |
      conda activate nthits
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits
