jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq software-properties-common
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
      sudo apt-get install -qq autoconf automake gcc g++ make
    displayName: Install common
  - script: |
      ./autogen.sh
      ./configure
      make distcheck
    displayName: Compiling ntHits
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-8
      sudo ln -sf clang-format-8 /usr/bin/clang-format
    displayName: Install clang-format
  - script: make clang-format
    displayName: Run clang-format
