jobs:

- job: linux
  pool:
    vmImage: 'ubuntu-22.04'
   
  steps:
  - checkout: self
    submodules: true

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda install --yes -c conda-forge mamba python=3.9
      mamba install --yes -c conda-forge -c bioconda --file requirements.txt
    displayName: Install dependencies

  - script: |
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits

- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'
  
  steps:
  - checkout: self
    submodules: true

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda install --yes -c conda-forge mamba python=3.9
      mamba install --yes -c conda-forge -c bioconda --file requirements.txt
    displayName: Install dependencies

  - script: |
      source activate nthits
      meson setup build 
      cd build
      ninja && ninja test
    displayName: Compile and test ntHits
